/**
 * Dünya ülkeleri (ISO 3166-1 alpha-2) — Türkçe adlarıyla, alfabetik.
 * Reklam ve kampanya hedeflemesinde ortak kullanılır.
 *
 * Kod backend'de {@code country_code VARCHAR(2)} olarak saklanır.
 */
export type Country = { code: string; ad: string };

export const COUNTRIES: Country[] = [
  { code: "AF", ad: "Afganistan" },
  { code: "DE", ad: "Almanya" },
  { code: "US", ad: "Amerika Birleşik Devletleri" },
  { code: "AD", ad: "Andorra" },
  { code: "AO", ad: "Angola" },
  { code: "AG", ad: "Antigua ve Barbuda" },
  { code: "AR", ad: "Arjantin" },
  { code: "AL", ad: "Arnavutluk" },
  { code: "AW", ad: "Aruba" },
  { code: "AU", ad: "Avustralya" },
  { code: "AT", ad: "Avusturya" },
  { code: "AZ", ad: "Azerbaycan" },
  { code: "BS", ad: "Bahamalar" },
  { code: "BH", ad: "Bahreyn" },
  { code: "BD", ad: "Bangladeş" },
  { code: "BB", ad: "Barbados" },
  { code: "BY", ad: "Belarus" },
  { code: "BE", ad: "Belçika" },
  { code: "BZ", ad: "Belize" },
  { code: "BJ", ad: "Benin" },
  { code: "BM", ad: "Bermuda" },
  { code: "AE", ad: "Birleşik Arap Emirlikleri" },
  { code: "GB", ad: "Birleşik Krallık" },
  { code: "BO", ad: "Bolivya" },
  { code: "BA", ad: "Bosna-Hersek" },
  { code: "BW", ad: "Botsvana" },
  { code: "BR", ad: "Brezilya" },
  { code: "BN", ad: "Brunei" },
  { code: "BG", ad: "Bulgaristan" },
  { code: "BF", ad: "Burkina Faso" },
  { code: "BI", ad: "Burundi" },
  { code: "BT", ad: "Butan" },
  { code: "CV", ad: "Cabo Verde" },
  { code: "DZ", ad: "Cezayir" },
  { code: "DJ", ad: "Cibuti" },
  { code: "CN", ad: "Çin" },
  { code: "TD", ad: "Çad" },
  { code: "CZ", ad: "Çekya" },
  { code: "DK", ad: "Danimarka" },
  { code: "DO", ad: "Dominik Cumhuriyeti" },
  { code: "DM", ad: "Dominika" },
  { code: "EC", ad: "Ekvador" },
  { code: "GQ", ad: "Ekvator Ginesi" },
  { code: "SV", ad: "El Salvador" },
  { code: "ID", ad: "Endonezya" },
  { code: "ER", ad: "Eritre" },
  { code: "AM", ad: "Ermenistan" },
  { code: "EE", ad: "Estonya" },
  { code: "SZ", ad: "Esvatini" },
  { code: "ET", ad: "Etiyopya" },
  { code: "MA", ad: "Fas" },
  { code: "FJ", ad: "Fiji" },
  { code: "CI", ad: "Fildişi Sahili" },
  { code: "PH", ad: "Filipinler" },
  { code: "PS", ad: "Filistin" },
  { code: "FI", ad: "Finlandiya" },
  { code: "FR", ad: "Fransa" },
  { code: "GA", ad: "Gabon" },
  { code: "GM", ad: "Gambiya" },
  { code: "GH", ad: "Gana" },
  { code: "GN", ad: "Gine" },
  { code: "GW", ad: "Gine-Bissau" },
  { code: "GD", ad: "Grenada" },
  { code: "GL", ad: "Grönland" },
  { code: "GT", ad: "Guatemala" },
  { code: "GY", ad: "Guyana" },
  { code: "ZA", ad: "Güney Afrika" },
  { code: "KR", ad: "Güney Kore" },
  { code: "SS", ad: "Güney Sudan" },
  { code: "GE", ad: "Gürcistan" },
  { code: "HT", ad: "Haiti" },
  { code: "IN", ad: "Hindistan" },
  { code: "HR", ad: "Hırvatistan" },
  { code: "NL", ad: "Hollanda" },
  { code: "HN", ad: "Honduras" },
  { code: "HK", ad: "Hong Kong" },
  { code: "IQ", ad: "Irak" },
  { code: "IR", ad: "İran" },
  { code: "IE", ad: "İrlanda" },
  { code: "ES", ad: "İspanya" },
  { code: "IL", ad: "İsrail" },
  { code: "SE", ad: "İsveç" },
  { code: "CH", ad: "İsviçre" },
  { code: "IT", ad: "İtalya" },
  { code: "IS", ad: "İzlanda" },
  { code: "JM", ad: "Jamaika" },
  { code: "JP", ad: "Japonya" },
  { code: "KH", ad: "Kamboçya" },
  { code: "CM", ad: "Kamerun" },
  { code: "CA", ad: "Kanada" },
  { code: "ME", ad: "Karadağ" },
  { code: "QA", ad: "Katar" },
  { code: "KZ", ad: "Kazakistan" },
  { code: "KE", ad: "Kenya" },
  { code: "CY", ad: "Kıbrıs" },
  { code: "KG", ad: "Kırgızistan" },
  { code: "KI", ad: "Kiribati" },
  { code: "CO", ad: "Kolombiya" },
  { code: "KM", ad: "Komorlar" },
  { code: "CG", ad: "Kongo Cumhuriyeti" },
  { code: "CD", ad: "Kongo Demokratik Cumhuriyeti" },
  { code: "XK", ad: "Kosova" },
  { code: "CR", ad: "Kosta Rika" },
  { code: "KW", ad: "Kuveyt" },
  { code: "KP", ad: "Kuzey Kore" },
  { code: "MK", ad: "Kuzey Makedonya" },
  { code: "CU", ad: "Küba" },
  { code: "LA", ad: "Laos" },
  { code: "LS", ad: "Lesotho" },
  { code: "LV", ad: "Letonya" },
  { code: "LR", ad: "Liberya" },
  { code: "LY", ad: "Libya" },
  { code: "LI", ad: "Liechtenstein" },
  { code: "LT", ad: "Litvanya" },
  { code: "LB", ad: "Lübnan" },
  { code: "LU", ad: "Lüksemburg" },
  { code: "HU", ad: "Macaristan" },
  { code: "MG", ad: "Madagaskar" },
  { code: "MO", ad: "Makao" },
  { code: "MW", ad: "Malavi" },
  { code: "MV", ad: "Maldivler" },
  { code: "MY", ad: "Malezya" },
  { code: "ML", ad: "Mali" },
  { code: "MT", ad: "Malta" },
  { code: "MH", ad: "Marshall Adaları" },
  { code: "MX", ad: "Meksika" },
  { code: "EG", ad: "Mısır" },
  { code: "FM", ad: "Mikronezya" },
  { code: "MN", ad: "Moğolistan" },
  { code: "MD", ad: "Moldova" },
  { code: "MC", ad: "Monako" },
  { code: "MR", ad: "Moritanya" },
  { code: "MU", ad: "Moritius" },
  { code: "MZ", ad: "Mozambik" },
  { code: "MM", ad: "Myanmar" },
  { code: "NA", ad: "Namibya" },
  { code: "NR", ad: "Nauru" },
  { code: "NP", ad: "Nepal" },
  { code: "NE", ad: "Nijer" },
  { code: "NG", ad: "Nijerya" },
  { code: "NI", ad: "Nikaragua" },
  { code: "NO", ad: "Norveç" },
  { code: "CF", ad: "Orta Afrika Cumhuriyeti" },
  { code: "UZ", ad: "Özbekistan" },
  { code: "PK", ad: "Pakistan" },
  { code: "PW", ad: "Palau" },
  { code: "PA", ad: "Panama" },
  { code: "PG", ad: "Papua Yeni Gine" },
  { code: "PY", ad: "Paraguay" },
  { code: "PE", ad: "Peru" },
  { code: "PL", ad: "Polonya" },
  { code: "PT", ad: "Portekiz" },
  { code: "PR", ad: "Porto Riko" },
  { code: "RO", ad: "Romanya" },
  { code: "RW", ad: "Ruanda" },
  { code: "RU", ad: "Rusya" },
  { code: "WS", ad: "Samoa" },
  { code: "SM", ad: "San Marino" },
  { code: "ST", ad: "São Tomé ve Príncipe" },
  { code: "SN", ad: "Senegal" },
  { code: "SC", ad: "Seyşeller" },
  { code: "SG", ad: "Singapur" },
  { code: "RS", ad: "Sırbistan" },
  { code: "SK", ad: "Slovakya" },
  { code: "SI", ad: "Slovenya" },
  { code: "SB", ad: "Solomon Adaları" },
  { code: "SO", ad: "Somali" },
  { code: "LK", ad: "Sri Lanka" },
  { code: "SD", ad: "Sudan" },
  { code: "SR", ad: "Surinam" },
  { code: "SA", ad: "Suudi Arabistan" },
  { code: "SY", ad: "Suriye" },
  { code: "CL", ad: "Şili" },
  { code: "TJ", ad: "Tacikistan" },
  { code: "TZ", ad: "Tanzanya" },
  { code: "TH", ad: "Tayland" },
  { code: "TW", ad: "Tayvan" },
  { code: "TG", ad: "Togo" },
  { code: "TO", ad: "Tonga" },
  { code: "TT", ad: "Trinidad ve Tobago" },
  { code: "TN", ad: "Tunus" },
  { code: "TR", ad: "Türkiye" },
  { code: "TM", ad: "Türkmenistan" },
  { code: "TV", ad: "Tuvalu" },
  { code: "UG", ad: "Uganda" },
  { code: "UA", ad: "Ukrayna" },
  { code: "OM", ad: "Umman" },
  { code: "UY", ad: "Uruguay" },
  { code: "JO", ad: "Ürdün" },
  { code: "VU", ad: "Vanuatu" },
  { code: "VA", ad: "Vatikan" },
  { code: "VE", ad: "Venezuela" },
  { code: "VN", ad: "Vietnam" },
  { code: "YE", ad: "Yemen" },
  { code: "NC", ad: "Yeni Kaledonya" },
  { code: "NZ", ad: "Yeni Zelanda" },
  { code: "GR", ad: "Yunanistan" },
  { code: "ZM", ad: "Zambiya" },
  { code: "ZW", ad: "Zimbabve" },
];

/** Reklam hacmi yüksek pazarlar — listenin başında ayrı grupta gösterilir. */
export const FEATURED_COUNTRIES = ["TR", "DE", "US", "GB", "NL", "FR", "AE", "AZ"];

export const countryName = (code: string) => COUNTRIES.find((u) => u.code === code)?.ad ?? code;
