/**
 * Dünya ülkeleri (ISO 3166-1 alpha-2) — Türkçe adlarıyla, alfabetik.
 * Reklam ve kampanya hedeflemesinde ortak kullanılır.
 *
 * Kod backend'de {@code country_code VARCHAR(2)} olarak saklanır.
 */
export type Ulke = { kod: string; ad: string };

export const COUNTRIES: Ulke[] = [
  { kod: "AF", ad: "Afganistan" },
  { kod: "DE", ad: "Almanya" },
  { kod: "US", ad: "Amerika Birleşik Devletleri" },
  { kod: "AD", ad: "Andorra" },
  { kod: "AO", ad: "Angola" },
  { kod: "AG", ad: "Antigua ve Barbuda" },
  { kod: "AR", ad: "Arjantin" },
  { kod: "AL", ad: "Arnavutluk" },
  { kod: "AW", ad: "Aruba" },
  { kod: "AU", ad: "Avustralya" },
  { kod: "AT", ad: "Avusturya" },
  { kod: "AZ", ad: "Azerbaycan" },
  { kod: "BS", ad: "Bahamalar" },
  { kod: "BH", ad: "Bahreyn" },
  { kod: "BD", ad: "Bangladeş" },
  { kod: "BB", ad: "Barbados" },
  { kod: "BY", ad: "Belarus" },
  { kod: "BE", ad: "Belçika" },
  { kod: "BZ", ad: "Belize" },
  { kod: "BJ", ad: "Benin" },
  { kod: "BM", ad: "Bermuda" },
  { kod: "AE", ad: "Birleşik Arap Emirlikleri" },
  { kod: "GB", ad: "Birleşik Krallık" },
  { kod: "BO", ad: "Bolivya" },
  { kod: "BA", ad: "Bosna-Hersek" },
  { kod: "BW", ad: "Botsvana" },
  { kod: "BR", ad: "Brezilya" },
  { kod: "BN", ad: "Brunei" },
  { kod: "BG", ad: "Bulgaristan" },
  { kod: "BF", ad: "Burkina Faso" },
  { kod: "BI", ad: "Burundi" },
  { kod: "BT", ad: "Butan" },
  { kod: "CV", ad: "Cabo Verde" },
  { kod: "DZ", ad: "Cezayir" },
  { kod: "DJ", ad: "Cibuti" },
  { kod: "CN", ad: "Çin" },
  { kod: "TD", ad: "Çad" },
  { kod: "CZ", ad: "Çekya" },
  { kod: "DK", ad: "Danimarka" },
  { kod: "DO", ad: "Dominik Cumhuriyeti" },
  { kod: "DM", ad: "Dominika" },
  { kod: "EC", ad: "Ekvador" },
  { kod: "GQ", ad: "Ekvator Ginesi" },
  { kod: "SV", ad: "El Salvador" },
  { kod: "ID", ad: "Endonezya" },
  { kod: "ER", ad: "Eritre" },
  { kod: "AM", ad: "Ermenistan" },
  { kod: "EE", ad: "Estonya" },
  { kod: "SZ", ad: "Esvatini" },
  { kod: "ET", ad: "Etiyopya" },
  { kod: "MA", ad: "Fas" },
  { kod: "FJ", ad: "Fiji" },
  { kod: "CI", ad: "Fildişi Sahili" },
  { kod: "PH", ad: "Filipinler" },
  { kod: "PS", ad: "Filistin" },
  { kod: "FI", ad: "Finlandiya" },
  { kod: "FR", ad: "Fransa" },
  { kod: "GA", ad: "Gabon" },
  { kod: "GM", ad: "Gambiya" },
  { kod: "GH", ad: "Gana" },
  { kod: "GN", ad: "Gine" },
  { kod: "GW", ad: "Gine-Bissau" },
  { kod: "GD", ad: "Grenada" },
  { kod: "GL", ad: "Grönland" },
  { kod: "GT", ad: "Guatemala" },
  { kod: "GY", ad: "Guyana" },
  { kod: "ZA", ad: "Güney Afrika" },
  { kod: "KR", ad: "Güney Kore" },
  { kod: "SS", ad: "Güney Sudan" },
  { kod: "GE", ad: "Gürcistan" },
  { kod: "HT", ad: "Haiti" },
  { kod: "IN", ad: "Hindistan" },
  { kod: "HR", ad: "Hırvatistan" },
  { kod: "NL", ad: "Hollanda" },
  { kod: "HN", ad: "Honduras" },
  { kod: "HK", ad: "Hong Kong" },
  { kod: "IQ", ad: "Irak" },
  { kod: "IR", ad: "İran" },
  { kod: "IE", ad: "İrlanda" },
  { kod: "ES", ad: "İspanya" },
  { kod: "IL", ad: "İsrail" },
  { kod: "SE", ad: "İsveç" },
  { kod: "CH", ad: "İsviçre" },
  { kod: "IT", ad: "İtalya" },
  { kod: "IS", ad: "İzlanda" },
  { kod: "JM", ad: "Jamaika" },
  { kod: "JP", ad: "Japonya" },
  { kod: "KH", ad: "Kamboçya" },
  { kod: "CM", ad: "Kamerun" },
  { kod: "CA", ad: "Kanada" },
  { kod: "ME", ad: "Karadağ" },
  { kod: "QA", ad: "Katar" },
  { kod: "KZ", ad: "Kazakistan" },
  { kod: "KE", ad: "Kenya" },
  { kod: "CY", ad: "Kıbrıs" },
  { kod: "KG", ad: "Kırgızistan" },
  { kod: "KI", ad: "Kiribati" },
  { kod: "CO", ad: "Kolombiya" },
  { kod: "KM", ad: "Komorlar" },
  { kod: "CG", ad: "Kongo Cumhuriyeti" },
  { kod: "CD", ad: "Kongo Demokratik Cumhuriyeti" },
  { kod: "XK", ad: "Kosova" },
  { kod: "CR", ad: "Kosta Rika" },
  { kod: "KW", ad: "Kuveyt" },
  { kod: "KP", ad: "Kuzey Kore" },
  { kod: "MK", ad: "Kuzey Makedonya" },
  { kod: "CU", ad: "Küba" },
  { kod: "LA", ad: "Laos" },
  { kod: "LS", ad: "Lesotho" },
  { kod: "LV", ad: "Letonya" },
  { kod: "LR", ad: "Liberya" },
  { kod: "LY", ad: "Libya" },
  { kod: "LI", ad: "Liechtenstein" },
  { kod: "LT", ad: "Litvanya" },
  { kod: "LB", ad: "Lübnan" },
  { kod: "LU", ad: "Lüksemburg" },
  { kod: "HU", ad: "Macaristan" },
  { kod: "MG", ad: "Madagaskar" },
  { kod: "MO", ad: "Makao" },
  { kod: "MW", ad: "Malavi" },
  { kod: "MV", ad: "Maldivler" },
  { kod: "MY", ad: "Malezya" },
  { kod: "ML", ad: "Mali" },
  { kod: "MT", ad: "Malta" },
  { kod: "MH", ad: "Marshall Adaları" },
  { kod: "MX", ad: "Meksika" },
  { kod: "EG", ad: "Mısır" },
  { kod: "FM", ad: "Mikronezya" },
  { kod: "MN", ad: "Moğolistan" },
  { kod: "MD", ad: "Moldova" },
  { kod: "MC", ad: "Monako" },
  { kod: "MR", ad: "Moritanya" },
  { kod: "MU", ad: "Moritius" },
  { kod: "MZ", ad: "Mozambik" },
  { kod: "MM", ad: "Myanmar" },
  { kod: "NA", ad: "Namibya" },
  { kod: "NR", ad: "Nauru" },
  { kod: "NP", ad: "Nepal" },
  { kod: "NE", ad: "Nijer" },
  { kod: "NG", ad: "Nijerya" },
  { kod: "NI", ad: "Nikaragua" },
  { kod: "NO", ad: "Norveç" },
  { kod: "CF", ad: "Orta Afrika Cumhuriyeti" },
  { kod: "UZ", ad: "Özbekistan" },
  { kod: "PK", ad: "Pakistan" },
  { kod: "PW", ad: "Palau" },
  { kod: "PA", ad: "Panama" },
  { kod: "PG", ad: "Papua Yeni Gine" },
  { kod: "PY", ad: "Paraguay" },
  { kod: "PE", ad: "Peru" },
  { kod: "PL", ad: "Polonya" },
  { kod: "PT", ad: "Portekiz" },
  { kod: "PR", ad: "Porto Riko" },
  { kod: "RO", ad: "Romanya" },
  { kod: "RW", ad: "Ruanda" },
  { kod: "RU", ad: "Rusya" },
  { kod: "WS", ad: "Samoa" },
  { kod: "SM", ad: "San Marino" },
  { kod: "ST", ad: "São Tomé ve Príncipe" },
  { kod: "SN", ad: "Senegal" },
  { kod: "SC", ad: "Seyşeller" },
  { kod: "SG", ad: "Singapur" },
  { kod: "RS", ad: "Sırbistan" },
  { kod: "SK", ad: "Slovakya" },
  { kod: "SI", ad: "Slovenya" },
  { kod: "SB", ad: "Solomon Adaları" },
  { kod: "SO", ad: "Somali" },
  { kod: "LK", ad: "Sri Lanka" },
  { kod: "SD", ad: "Sudan" },
  { kod: "SR", ad: "Surinam" },
  { kod: "SA", ad: "Suudi Arabistan" },
  { kod: "SY", ad: "Suriye" },
  { kod: "CL", ad: "Şili" },
  { kod: "TJ", ad: "Tacikistan" },
  { kod: "TZ", ad: "Tanzanya" },
  { kod: "TH", ad: "Tayland" },
  { kod: "TW", ad: "Tayvan" },
  { kod: "TG", ad: "Togo" },
  { kod: "TO", ad: "Tonga" },
  { kod: "TT", ad: "Trinidad ve Tobago" },
  { kod: "TN", ad: "Tunus" },
  { kod: "TR", ad: "Türkiye" },
  { kod: "TM", ad: "Türkmenistan" },
  { kod: "TV", ad: "Tuvalu" },
  { kod: "UG", ad: "Uganda" },
  { kod: "UA", ad: "Ukrayna" },
  { kod: "OM", ad: "Umman" },
  { kod: "UY", ad: "Uruguay" },
  { kod: "JO", ad: "Ürdün" },
  { kod: "VU", ad: "Vanuatu" },
  { kod: "VA", ad: "Vatikan" },
  { kod: "VE", ad: "Venezuela" },
  { kod: "VN", ad: "Vietnam" },
  { kod: "YE", ad: "Yemen" },
  { kod: "NC", ad: "Yeni Kaledonya" },
  { kod: "NZ", ad: "Yeni Zelanda" },
  { kod: "GR", ad: "Yunanistan" },
  { kod: "ZM", ad: "Zambiya" },
  { kod: "ZW", ad: "Zimbabve" },
];

/** Reklam hacmi yüksek pazarlar — listenin başında ayrı grupta gösterilir. */
export const FEATURED_COUNTRIES = ["TR", "DE", "US", "GB", "NL", "FR", "AE", "AZ"];

export const countryName = (kod: string) => COUNTRIES.find((u) => u.kod === kod)?.ad ?? kod;
